//! Detection of the credit a commit message or a pull request body gives an AI for the work.
//!
//! This repository is written with an assistant and talks about one constantly, so naming a model
//! is not the offence and cannot be made into one: a scan that fired on the word `Claude` would
//! fire on nearly every commit here. The offence is narrower. It is a line that puts a model where
//! the name of whoever did the work belongs -- in the value of a trailer that names an author, or
//! in the clause a phrase that credits its object opens -- and it is an address at a vendor's own
//! domain, which is an identity rather than prose wherever it is written.
//!
//! So a line is read for the shape of a credit rather than for a name. `Co-authored-by: Claude` is
//! caught by its key, `Generated with [Claude Code]` by the phrase the name is the object of, and
//! `noreply@anthropic.com` by being an address nobody writes about. `Claude Code laid this guard
//! out` is prose, names no author, and passes.
//!
//! Where the name sits is what separates the two. A phrase credits the party named in the clause
//! it opens and nothing further along the line, so `generated with a script that Claude Code once
//! suggested` says a script did the work and is left alone, while `generated with Claude Code`
//! says a model did and is not. A trailer's value is read whole instead, because a value is an
//! identity all the way to the end of the line rather than a sentence a name can honestly appear
//! in.

use std::fmt::{Display, Formatter, Result as FmtResult};

/// The names an AI, a model, or an assistant is credited under, each of which stands for one
/// wherever it is written.
pub const AI_NAMES: [&str; 12] = [
    "ai",
    "anthropic",
    "assistant",
    "chatgpt",
    "claude",
    "codex",
    "copilot",
    "cursor",
    "devin",
    "gemini",
    "gpt",
    "openai",
];

/// The names of models that are ordinary words besides, which therefore stand for a model only
/// where the line has already said it is naming whoever did the work.
pub const MODEL_NAMES: [&str; 4] = ["haiku", "llama", "opus", "sonnet"];

/// The trailer keys whose value names whoever the work is owed to.
pub const CREDIT_KEYS: [&str; 9] = [
    "assisted-by",
    "author",
    "authored-by",
    "co-author",
    "co-authored-by",
    "co-developed-by",
    "committer",
    "generated-by",
    "signed-off-by",
];

/// The phrases that credit whatever is written directly after them with having produced the work.
pub const CREDIT_PHRASES: [&str; 8] = [
    "assisted by",
    "authored by",
    "co-authored by",
    "created by",
    "generated by",
    "generated with",
    "produced by",
    "written by",
];

/// The mail domains an AI vendor's own identity is written at.
pub const VENDOR_DOMAINS: [&str; 2] = ["anthropic.com", "openai.com"];

/// How many words of a clause a phrase can credit. `Assisted by GitHub Copilot` credits two, and
/// nothing anybody signs work over to is named in more, so a model written further along than this
/// is one the sentence went on to mention rather than the party being thanked.
pub const CREDITED_WORDS: usize = 3;

/// What made a line a credit.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Reason {
    /// A trailer naming an author holds a model in its value, holding the trailer's key.
    Trailer(String),

    /// A phrase crediting whatever follows it is followed by a model, holding the phrase.
    Phrase(String),

    /// An address at a vendor's own domain, holding the domain.
    Address(String),
}

impl Display for Reason {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> FmtResult {
        match self {
            Self::Trailer(key) => write!(formatter, "`{key}:` names a model as an author"),
            Self::Phrase(phrase) => write!(formatter, "`{phrase}` is followed by a model"),
            Self::Address(domain) => write!(formatter, "`{domain}` is an AI vendor's own domain"),
        }
    }
}

/// A credit found in a text, which is the line that gives it and what made it one.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Credit {
    line: usize,
    text: String,
    reason: Reason,
}

impl Credit {
    /// # Returns
    ///
    /// The line of the text the credit is written on, counted from one.
    #[must_use]
    pub fn line(&self) -> usize {
        self.line
    }

    /// # Returns
    ///
    /// The line as it is written, with the space around it trimmed.
    #[must_use]
    pub fn text(&self) -> &str {
        &self.text
    }

    /// # Returns
    ///
    /// What made the line a credit.
    #[must_use]
    pub fn reason(&self) -> &Reason {
        &self.reason
    }
}

impl Display for Credit {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> FmtResult {
        write!(
            formatter,
            "line {}: {}: {}",
            self.line, self.reason, self.text
        )
    }
}

/// Scans a commit message or a pull request body for credit given to an AI.
///
/// # Returns
///
/// Every line of the text that credits an AI as an author or as a generator, in the order they are
/// written, empty where none does.
#[must_use]
pub fn scan(text: &str) -> Vec<Credit> {
    text.lines()
        .enumerate()
        .filter_map(|(at, line)| {
            credited(line).map(|reason| Credit {
                line: at + 1,
                text: line.trim().to_owned(),
                reason,
            })
        })
        .collect()
}

/// # Returns
///
/// What makes one line a credit, or [`None`] where nothing does.
fn credited(line: &str) -> Option<Reason> {
    let line = line.trim().to_lowercase();

    if let Some(key) = credit_trailer(&line) {
        return Some(Reason::Trailer(key));
    }
    if let Some(phrase) = credit_phrase(&line) {
        return Some(Reason::Phrase(phrase));
    }
    for domain in VENDOR_DOMAINS {
        if line.contains(&format!("@{domain}")) {
            return Some(Reason::Address(domain.to_owned()));
        }
    }

    None
}

/// # Returns
///
/// The key of the trailer a line gives a model in the value of, or [`None`] where the line is no
/// such trailer. The whole value is read, because a trailer's value is an identity rather than a
/// sentence a name can appear in for another reason.
fn credit_trailer(line: &str) -> Option<String> {
    let (key, value) = line.split_once(':')?;
    if key.is_empty() || key.split_whitespace().count() != 1 {
        return None;
    }
    if !CREDIT_KEYS.contains(&key) {
        return None;
    }
    tokens(value)
        .iter()
        .any(|token| names_ai(token) || names_model(token))
        .then(|| key.to_owned())
}

/// # Returns
///
/// The phrase a line credits a model through, or [`None`] where the line holds no such phrase.
/// Only the party named in the clause a phrase opens is read, so a phrase that credits something
/// else names something else however the rest of the line goes on.
fn credit_phrase(line: &str) -> Option<String> {
    for phrase in CREDIT_PHRASES {
        let mut rest = line;
        while let Some(at) = rest.find(phrase) {
            let after = &rest[at + phrase.len()..];
            if credited_party(after).iter().any(|token| names_ai(token)) {
                return Some(phrase.to_owned());
            }
            rest = after;
        }
    }

    None
}

/// # Returns
///
/// The words naming whoever a phrase credits, which run from the phrase to the end of the clause
/// and no further than a name goes. A name is a handful of words, so a model further along the
/// line than that is a model the sentence went on to mention rather than the party being thanked.
fn credited_party(after: &str) -> Vec<&str> {
    let clause = after
        .char_indices()
        .find(|(at, character)| {
            matches!(character, ',' | ';' | '!' | '?')
                || ('.' == *character
                    && after[at + 1..]
                        .chars()
                        .next()
                        .is_none_or(char::is_whitespace))
        })
        .map_or(after.len(), |(at, _)| at);

    tokens(&after[..clause])
        .into_iter()
        .take(CREDITED_WORDS)
        .collect()
}

/// # Returns
///
/// The words of a lowercased line, in the order they are written. A word runs over the letters,
/// the digits and the separators a name is written with, so `claude-code` and `anthropic.com` are
/// each one word rather than several.
fn tokens(text: &str) -> Vec<&str> {
    text.split(|character: char| {
        !character.is_ascii_alphanumeric() && !matches!(character, '-' | '.' | '_')
    })
    .map(|token| token.trim_matches(['-', '.', '_']))
    .filter(|token| !token.is_empty())
    .collect()
}

/// # Returns
///
/// Whether a lowercased word names an AI, which `claude-code`, `gpt-4` and `anthropic.com` each do
/// through the name they open with.
fn names_ai(token: &str) -> bool {
    AI_NAMES.contains(&head(token))
}

/// # Returns
///
/// Whether a lowercased word names a model that is an ordinary word besides.
fn names_model(token: &str) -> bool {
    MODEL_NAMES.contains(&head(token))
}

/// # Returns
///
/// The name a word opens with, which is the word itself where it is written without separators.
fn head(token: &str) -> &str {
    token
        .split(['-', '.', '_'])
        .next()
        .expect("splitting a word yields at least one part")
}

#[cfg(test)]
mod tests {
    use super::{scan, Reason};

    /// The trailer the repository's own history carries, which is the credit this module was
    /// written for.
    const OFFENCE: &str = "Co-authored-by: Claude Opus 5 (1M context) <noreply@anthropic.com>";

    /// # Returns
    ///
    /// Whether a text credits an AI anywhere.
    fn credits(text: &str) -> bool {
        !scan(text).is_empty()
    }

    #[test]
    fn the_trailer_the_history_carries_is_caught() {
        let message = format!("ci: Do a thing.\n\nA body that explains it.\n\n{OFFENCE}\n");
        let credits = scan(&message);

        assert_eq!(1, credits.len(), "{credits:?}");
        assert_eq!(5, credits[0].line());
        assert_eq!(
            &Reason::Trailer("co-authored-by".to_owned()),
            credits[0].reason()
        );
    }

    #[test]
    fn the_case_a_credit_is_written_in_does_not_matter() {
        for written in [
            OFFENCE,
            &OFFENCE.to_uppercase(),
            &OFFENCE.to_lowercase(),
            "Co-Authored-By: Claude",
            "co-authored-by: claude",
            "CO-AUTHORED-BY: CLAUDE",
        ] {
            assert!(credits(written), "`{written}` was passed");
        }
    }

    #[test]
    fn a_generator_a_body_thanks_is_caught() {
        for written in [
            "Generated with [Claude Code](https://claude.com/claude-code)",
            "generated with claude code",
            "GENERATED WITH CLAUDE",
            "This patch was written by Claude.",
            "Produced by ChatGPT, reviewed by a human.",
            "Assisted by GitHub Copilot.",
            "Generated with the Claude Code CLI.",
            "Co-authored by the assistant at the other end.",
            "Generated with: Claude Code",
        ] {
            assert!(credits(written), "`{written}` was passed");
        }
    }

    #[test]
    fn an_address_at_a_vendors_own_domain_is_caught() {
        for written in [
            "noreply@anthropic.com",
            "See NOREPLY@ANTHROPIC.COM for the identity.",
            "someone@openai.com",
        ] {
            assert!(credits(written), "`{written}` was passed");
        }
    }

    #[test]
    fn a_model_named_in_a_trailer_is_caught_by_the_trailer() {
        for written in [
            "Co-authored-by: Opus",
            "Signed-off-by: Sonnet <a@b.example>",
            "Generated-by: Llama 3",
            "Author: Haiku",
        ] {
            assert!(credits(written), "`{written}` was passed");
        }
    }

    #[test]
    fn a_clean_message_passes() {
        let message = "ci: Fail a build that credits a model.\n\n\
             The rule lived in prose and was broken anyway, so it is a build step now.\n\n\
             Signed-off-by: Pleiades <pleiades@example.com>\n";

        assert_eq!(Vec::<super::Credit>::new(), scan(message));
    }

    #[test]
    fn prose_that_merely_names_a_model_passes() {
        for written in [
            "The editor is written at a terminal beside Claude Code.",
            "Claude Code is the harness this repository is developed in.",
            "Anthropic publishes the harness the repository is written with.",
            "This corrects a layout Claude Code got wrong.",
            "Add a guard so that a commit crediting Claude Code fails the build.",
            "Refer to the assistant only where the licence asks for it.",
            "The reader at claude.ai/code/session_0 is not an author.",
        ] {
            assert!(!credits(written), "`{written}` was failed");
        }
    }

    #[test]
    fn a_phrase_that_credits_something_else_passes() {
        for written in [
            "Generated with a script, which Claude Code did not write.",
            "The baseline was produced by vim rather than by Claude.",
            "Written by hand, unlike the Claude Code transcript beside it.",
            "Generated by cargo, whose output Claude Code read.",
            "Generated with the script the guard reads, not with Claude Code.",
            "Written by a person who had Claude Code open beside them.",
        ] {
            assert!(!credits(written), "`{written}` was failed");
        }
    }

    #[test]
    fn a_human_co_author_passes() {
        for written in [
            "Co-authored-by: Pleiades <pleiades@example.com>",
            "Signed-off-by: A Person <person@example.org>",
            "Reviewed-by: Claude Code",
        ] {
            assert!(!credits(written), "`{written}` was failed");
        }
    }

    #[test]
    fn every_line_of_a_message_is_read() {
        let message = format!("ci: Do a thing.\n\n{OFFENCE}\n\nGenerated with Claude Code\n");
        let credits = scan(&message);

        assert_eq!(
            vec![3, 5],
            credits.iter().map(super::Credit::line).collect::<Vec<_>>()
        );
    }
}
