//! Searches for a block, a set of spans, a width, and a set of display options on which applying
//! styles disturbs the rows the text is laid out into.
//!
//! Styling is a projection over a source that stays as it was, so the three things worth searching
//! for are the three ways a projection can lie: rows that draw something other than what the
//! layout drew, segments that name bytes other than the ones they render, and spans that cut a
//! grapheme cluster in half.
//!
//! The generated spans are byte ranges taken without regard for where a cluster begins or ends,
//! reach past the end of the source, and overlap one another, which are the three shapes a caller
//! hands over when the ranges came from somewhere else.

use std::num::NonZeroUsize;
use std::ops::Range;

use proptest::prelude::*;
use ratatui::style::{Color, Modifier};
use vbc_editor::style::{Block, Span, Style};
use vbc_layout::line::{self, DisplayRow, Options};
use vbc_layout::width::{grapheme_indices, graphemes, AmbiWidth, Metrics};

/// The graphemes sources are generated from, covering plain, break, tab, combining, ambiguous, and
/// double-width text, so a generated byte range lands inside a multi-byte cluster often.
const ALPHABET: [&str; 9] = ["a", "b", " ", "-", "\t", "é", "e\u{0301}", "漢", "α"];

/// The continuation markers the search runs with, whose decoration a styled row has to carry
/// without styling it.
const MARKERS: [&str; 4] = ["", "> ", "+", "\u{21B3} "];

/// The bounds a generated case is drawn from. A source holds several logical lines so that a span
/// is addressed against the whole source rather than against the line it happens to fall in.
const MAX_LINES: usize = 3;
const MAX_LINE_LEN: usize = 16;
const MAX_SPANS: usize = 6;
const MAX_SPAN_LEN: usize = 10;
const MIN_WIDTH: usize = 2;
const MAX_WIDTH: usize = 10;
const MAX_BREAK_INDENT_MIN: usize = 12;

/// The number of cases each search runs.
const CASES: u32 = 16_384;

/// One generated case: the block being drawn, the spans it was built from before they were widened
/// to the clusters they land in, and the way its lines are laid out.
#[derive(Clone, Debug)]
struct Case {
    block: Block,
    given: Vec<Span>,
    width: NonZeroUsize,
    metrics: Metrics,
    options: Options,
}

impl Case {
    /// # Returns
    ///
    /// Each logical line of the block, the rows it is laid out into, and the styled rows those
    /// rows are drawn as.
    fn rendered(&self) -> Vec<(usize, Vec<DisplayRow>)> {
        self.block
            .lines()
            .enumerate()
            .map(|(line, (start, text))| {
                (
                    start,
                    line::lay_out(line, text, self.width, self.metrics, &self.options),
                )
            })
            .collect()
    }
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: CASES,
        failure_persistence: None,
        ..ProptestConfig::default()
    })]

    #[test]
    fn styling_never_moves_a_character(case in case()) {
        for (start, rows) in case.rendered() {
            let styled = case.block.style_rows(start, &rows);
            prop_assert_eq!(
                rows.len(),
                styled.len(),
                "the styled rows do not match the rows they were built from: {:?}",
                case
            );

            for (index, (row, styled_row)) in rows.iter().zip(&styled).enumerate() {
                let cells = styled_row.cells();
                prop_assert_eq!(
                    row.cells(),
                    cells.as_str(),
                    "row {} is drawn differently once styled: {:?}",
                    index,
                    case
                );
                prop_assert_eq!(
                    graphemes(row.cells()).collect::<Vec<&str>>(),
                    graphemes(&cells).collect::<Vec<&str>>(),
                    "row {} shows a different grapheme sequence once styled: {:?}",
                    index,
                    case
                );
                prop_assert_eq!(
                    row.prefix(),
                    styled_row.prefix(),
                    "row {} carries a different decoration once styled: {:?}",
                    index,
                    case
                );
            }
        }
    }

    #[test]
    fn a_segment_names_the_source_it_renders(case in case()) {
        for (line_start, rows) in case.rendered() {
            let styled = case.block.style_rows(line_start, &rows);
            let mut start = line_start;
            for (index, (row, styled_row)) in rows.iter().zip(&styled).enumerate() {
                let end = start + row.text().len();
                let mut offset = start;
                let mut rejoined = String::new();
                for segment in styled_row.segments() {
                    prop_assert_eq!(
                        offset,
                        segment.source().start,
                        "a segment of row {} does not start where the one before it ended: {:?}",
                        index,
                        case
                    );
                    let source = case
                        .block
                        .slice(segment.source().clone())
                        .expect("a segment names a range of the source");
                    prop_assert!(
                        !source.is_empty(),
                        "a segment of row {index} renders no source at all: {case:?}"
                    );
                    rejoined.push_str(source);
                    offset = segment.source().end;
                }

                prop_assert_eq!(
                    offset,
                    end,
                    "the segments of row {} stop short of the row: {:?}",
                    index,
                    case
                );
                prop_assert_eq!(
                    &rejoined,
                    row.text(),
                    "the segments of row {} name text the row does not show: {:?}",
                    index,
                    case
                );

                for pair in styled_row.segments().windows(2) {
                    let &[left, right] = &pair else {
                        continue;
                    };
                    prop_assert_ne!(
                        left.style(),
                        right.style(),
                        "row {} is split into two segments drawn the same way: {:?}",
                        index,
                        case
                    );
                }
                for segment in styled_row.segments() {
                    let drawn = graphemes(&row.text()[..segment.source().start - start]).count();
                    prop_assert_eq!(
                        row.columns()[drawn],
                        segment.column(),
                        "a segment of row {} starts at a column the row does not draw it at: {:?}",
                        index,
                        case
                    );
                }

                start = end;
            }
        }
    }

    #[test]
    fn a_segment_is_drawn_in_the_style_of_the_last_span_covering_it(case in case()) {
        for (start, rows) in case.rendered() {
            for styled_row in case.block.style_rows(start, &rows) {
                for segment in styled_row.segments() {
                    let source = case
                        .block
                        .slice(segment.source().clone())
                        .expect("a segment names a range of the source");
                    for (offset, _) in grapheme_indices(source) {
                        let at = segment.source().start + offset;
                        let painted = case
                            .block
                            .spans()
                            .iter()
                            .rev()
                            .find(|span| span.range().contains(&at))
                            .map_or_else(Style::default, Span::style);
                        prop_assert_eq!(
                            painted,
                            segment.style(),
                            "the byte at {} is not drawn as the spans covering it ask: {:?}",
                            at,
                            case
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn a_span_never_splits_a_cluster(case in case()) {
        let source = case.block.source();
        let boundaries: Vec<usize> = boundaries(source);
        let given: Vec<&Span> = case
            .given
            .iter()
            .filter(|span| {
                span.range().start.min(source.len()) < span.range().end.min(source.len())
            })
            .collect();

        prop_assert_eq!(
            given.len(),
            case.block.spans().len(),
            "the block dropped a span that covers text, or kept one that covers none: {:?}",
            case
        );
        for (span, widened) in given.iter().zip(case.block.spans()) {
            let start = span.range().start.min(source.len());
            let end = span.range().end.min(source.len());
            let reached = boundaries
                .iter()
                .rev()
                .find(|&&boundary| boundary <= start)
                .copied()
                .expect("a source begins on a cluster boundary");
            let past = boundaries
                .iter()
                .find(|&&boundary| end <= boundary)
                .copied()
                .expect("a source ends on a cluster boundary");
            prop_assert_eq!(
                reached..past,
                widened.range().clone(),
                "a span is drawn from something other than the clusters it lands in: {:?}",
                case
            );
        }

        for (start, rows) in case.rendered() {
            for styled_row in case.block.style_rows(start, &rows) {
                for segment in styled_row.segments() {
                    prop_assert!(
                        boundaries.contains(&segment.source().start)
                            && boundaries.contains(&segment.source().end),
                        "a segment is drawn from inside a cluster: {case:?}"
                    );
                }
            }
        }
    }
}

/// # Returns
///
/// Every byte offset of `source` a grapheme cluster may begin or end at.
fn boundaries(source: &str) -> Vec<usize> {
    grapheme_indices(source)
        .map(|(offset, _)| offset)
        .chain(std::iter::once(source.len()))
        .collect()
}

/// # Returns
///
/// The styles a generated span is drawn in, the default among them so that a span painting nothing
/// visible is searched over too.
fn styles() -> Vec<Style> {
    vec![
        Style::default(),
        Style::new().fg(Color::Red),
        Style::new().bg(Color::Blue),
        Style::new().add_modifier(Modifier::BOLD),
    ]
}

/// # Returns
///
/// A strategy generating the blocks, widths, metrics, and options styling is searched over.
fn case() -> impl Strategy<Value = Case> {
    (
        styled_source(),
        MIN_WIDTH..=MAX_WIDTH,
        any::<bool>(),
        proptest::sample::select(MARKERS.as_slice()),
        any::<bool>(),
        0..=MAX_BREAK_INDENT_MIN,
        any::<bool>(),
    )
        .prop_flat_map(|generated| {
            let width = generated.1;
            (Just(generated), 1..=width)
        })
        .prop_map(
            |(
                (
                    (source, given),
                    width,
                    break_indent,
                    marker,
                    line_break,
                    break_indent_min,
                    wide_ambiguous,
                ),
                tab_stop,
            )| {
                let ambiwidth = if wide_ambiguous {
                    AmbiWidth::Double
                } else {
                    AmbiWidth::Single
                };
                Case {
                    block: Block::with_spans(source, given.clone()),
                    given,
                    width: NonZeroUsize::new(width).expect("a generated width is at least two"),
                    metrics: Metrics::new(
                        ambiwidth,
                        NonZeroUsize::new(tab_stop).expect("a generated tab stop is at least one"),
                    ),
                    options: Options::new()
                        .with_break_indent(break_indent)
                        .with_break_indent_min(break_indent_min)
                        .with_show_break(marker.to_owned())
                        .with_line_break(line_break),
                }
            },
        )
}

/// # Returns
///
/// A strategy generating a source and the spans styling it, whose ranges are taken without regard
/// for the clusters of the source and may reach past its end.
fn styled_source() -> impl Strategy<Value = (String, Vec<Span>)> {
    let line = proptest::collection::vec(
        proptest::sample::select(ALPHABET.as_slice()),
        0..=MAX_LINE_LEN,
    )
    .prop_map(|line_graphemes| line_graphemes.concat());

    proptest::collection::vec(line, 1..=MAX_LINES)
        .prop_map(|lines| lines.join("\n"))
        .prop_flat_map(|source| {
            let ranges = proptest::collection::vec(
                (
                    0..=source.len(),
                    0..=MAX_SPAN_LEN,
                    proptest::sample::select(styles()),
                ),
                0..=MAX_SPANS,
            );
            (Just(source), ranges)
        })
        .prop_map(|(source, ranges)| {
            let spans = ranges
                .into_iter()
                .map(|(start, length, style)| {
                    Span::new(
                        Range {
                            start,
                            end: start + length,
                        },
                        style,
                    )
                })
                .collect();
            (source, spans)
        })
}
